name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - wandb
      - jupyterlab
      - seaborn
      - pandas
      - matplotlib
      - numpy
      - plotly
      - pyarrow