name: train_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - wandb
      - pandas
      - mlflow
      - scikit-learn
      - numpy
      - xgboost
  